services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    depends_on:
      - otel-collector

  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"
    depends_on:
      - otel-collector

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    ports:
      - "8082:80"
      - "5341:5341"
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: QPGJbQvw2Ug6oKsR2pQI4OHh5Q3jhJlqTJ5IpaYZJ7a0P+phQLbS2aic3nTrKXjoyPxDf/keJrAZEdiInN+v/2u4+8/zxIPySjmonW8536+m
      SEQ_STORAGE_SECRETKEY: 9kPXGf5bWYlak8uerHRKbHZxOUuZPxP7AjMjHTWTX74=
    depends_on:
      - otel-collector

  aspire-dashboard:
    # https://azure.microsoft.com/pt-br/products/category/containers/
    # https://learn.microsoft.com/pt-br/dotnet/core/diagnostics/observability-otlp-example
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name: aspire-dashboard
    restart: always
    ports:
      - 18888:18888
      - 18889:18889
    environment:
      #- DASHBOARD__OTLP__AUTHMODE=ApiKey
      #- DASHBOARD__OTLP__PRIMARYAPIKEY=RQD9sGhdURmTAfp9UpsjSmSNm72yC2zn20QFYeoyfI0=
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension

  goapp1:
    container_name: goapp1
    build:
      context: go/.
    image: robsondevbr/goapp:latest
    environment:
      - TITLE=Microservice Demo
      - CONTENT=This is a demo of a microservice
      - BACKGROUND_COLOR=green
      - RESPONSE_TIME=1000
      - EXTERNAL_CALL_URL=http://goapp2:8181
      - EXTERNAL_CALL_METHOD=GET
      - REQUEST_NAME_OTEL=microservice-demo-request
      - OTEL_SERVICE_NAME=microservice-demo
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=:8080
      #- OTEL_EXPORTER_OTLP_HEADERS=RQD9sGhdURmTAfp9UpsjSmSNm72yC2zn20QFYeoyfI0=
    ports:
      - "8080:8080"
    depends_on:
      - goapp2
      - jaeger-all-in-one
      - zipkin-all-in-one
      - prometheus
      - otel-collector
      - seq

  goapp2:
    container_name: goapp2
    build:
      context: go/.
    image: robsondevbr/goapp:latest
    environment:
      - TITLE=Microservice Demo 2
      - CONTENT=This is a demo of a microservice
      - BACKGROUND_COLOR=blue
      - EXTERNAL_CALL_URL=http://goapp3:8282
      - EXTERNAL_CALL_METHOD=GET
      - RESPONSE_TIME=2000
      - REQUEST_NAME_OTEL=microservice-demo2-request
      - OTEL_SERVICE_NAME=microservice-demo2
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=:8181
      #- OTEL_EXPORTER_OTLP_HEADERS=RQD9sGhdURmTAfp9UpsjSmSNm72yC2zn20QFYeoyfI0=
    ports:
      - "8181:8181"
    depends_on:
      - goapp3 
      - jaeger-all-in-one
      - zipkin-all-in-one
      - prometheus
      - otel-collector
      - seq

  goapp3:
    container_name: goapp3
    build:
      context: go/.
    image: robsondevbr/goapp:latest
    environment:
      - TITLE=Microservice Demo 3
      - CONTENT=This is a demo of a microservice
      - BACKGROUND_COLOR=green
      - RESPONSE_TIME=2000
      - REQUEST_NAME_OTEL=microservice-demo3-request
      - OTEL_SERVICE_NAME=microservice-demo3
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=:8282
      #- OTEL_EXPORTER_OTLP_HEADERS=RQD9sGhdURmTAfp9UpsjSmSNm72yC2zn20QFYeoyfI0=
    ports:
      - "8282:8282"
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
      - prometheus
      - otel-collector
      - seq

  dotnet_opentelemetry_1:
    container_name: dotnet_opentelemetry_1
    build:
      context: dotnet/dotnet_opentelemetry/opentelemetry/.
    image: robsondevbr/dotnet_opentelemetry:latest
    ports:
      - "8090:8080"
      - "8091:8081"
    environment:
      - INSTANCE_NAME=dotnet_opentelemetry_1
      - OTEL_SERVICE_NAME=dotnet_opentelemetry_1
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc
      - OTEL_LOG_LEVEL=debug
      #- OTEL_EXPORTER_OTLP_HEADERS=RQD9sGhdURmTAfp9UpsjSmSNm72yC2zn20QFYeoyfI0=
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
      - prometheus
      - otel-collector
      - seq

  dotnet_opentelemetry_2:
    container_name: dotnet_opentelemetry_2
    build:
      context: dotnet/dotnet_opentelemetry/opentelemetry/.
    image: robsondevbr/dotnet_opentelemetry:latest
    ports:
      - "8092:8080"
      - "8093:8081"
    environment:
      - INSTANCE_NAME=dotnet_opentelemetry_2
      - OTEL_SERVICE_NAME=dotnet_opentelemetry_2
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc
      - OTEL_LOG_LEVEL=debug
      #- OTEL_EXPORTER_OTLP_HEADERS=RQD9sGhdURmTAfp9UpsjSmSNm72yC2zn20QFYeoyfI0=
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
      - prometheus
      - otel-collector
      - seq