receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  # Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

  # Zipkin
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  # Jaeger
  otlp/jaeger:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true

  # Seq
  otlphttp/seq:
    endpoint: http://seq:5341/ingest/otlp
    tls:
      insecure: true
    

processors:
  batch:

  filter/remove_route:
      error_mode: ignore
      logs:
        log_record:
          - resource.attributes["request.uri"] == "/favicon.ico"

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, filter/remove_route]
      exporters: [zipkin, otlp/jaeger, otlphttp/seq]
    metrics:
      receivers: [otlp]
      processors: [batch, filter/remove_route]
      exporters: [prometheus, otlphttp/seq]
    logs:
      receivers: [otlp]
      processors: [batch, filter/remove_route]
      exporters: [otlphttp/seq]